version: '1.0'

services:
  astro-ssr:
    build: .
    container_name: astro-ssr-container
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    # ⬅️ Ejecuta tu archivo `entry.mjs` este es el punto de entrada de tu aplicación Astro
    command: node dist/server/entry.mjs
