version: '3.8'

services:
  astro-ssr:
    build: .
    container_name: astro-ssr-container
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - astro_node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    command: node dist/server/entry.mjs
    depends_on:
      - minio-storage
# Despliega un contenedor para blobs de almacenamiento S3 compatible con MinIO
  minio-storage:
    image: minio/minio
    container_name: minio-storage-container
    ports:
      - "9000:9000"   # API S3 compatible
      - "9001:9001"   # Consola web
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9001"

volumes:
  astro_node_modules:
  minio_data:
