services:
  astro-ssr:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: astro-ssr-container
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
      - PUBLIC_API_URL=http://api:5000/api/auth
    command: node dist/server/entry.mjs
    depends_on:
      - api
    networks:
      - mr_menus_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-container
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    working_dir: /app
    command: dotnet Api.dll
    networks:
      - mr_menus_network

  # =========================
  # FTP Server (Almacenamiento)
  # =========================
  ftp_server:
    image: fauria/vsftpd
    container_name: mr_menus_ftp
    environment:
      FTP_USER: mrmenusftp
      FTP_PASS: MrMenusFtp123!
      FTP_CHROOT_LOCAL_USER: "YES"

      # 🔑 MODO PASIVO (OBLIGATORIO)
      PASV_ENABLE: "YES"
      PASV_ADDRESS: invboxv-app.com
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110

      # 🔐 PERMISOS DE ARCHIVOS
      FILE_OPEN_MODE: "0666"
      LOCAL_UMASK: "022"
    volumes:
      - files_data:/home/vsftpd/mrmenusftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    restart: always
    networks:
      - mr_menus_network

  # =========================
  # Nginx – Servidor público de archivos
  # =========================
  file_server:
    image: nginx:alpine
    container_name: mr_menus_file_server
    volumes:
      - files_data:/usr/share/nginx/html:ro
    ports:
      - "9003:80"
    restart: always
    networks:
      - mr_menus_network

volumes:
  files_data:

# =========================
# Red
# =========================
networks:
  mr_menus_network:
    driver: bridge