version: '3.8'

services:
  astro-ssr:
    build: .
    container_name: astro-ssr-container
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - astro_node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    command: node dist/server/entry.mjs
    depends_on:
      - ftp-storage
      - nginx-storage

  ftp-storage:
    image: stilliard/pure-ftpd:hardened
    container_name: ftp-storage-container
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=127.0.0.1
      - FTP_USER_NAME=usuario
      - FTP_USER_PASS=clave123
      - FTP_USER_HOME=/home/vsftpd
      - ADDED_FLAGS=--passiveportrange 30000:30009
    volumes:
      - ftp_data:/home/vsftpd

  nginx-storage:
    image: nginx:alpine
    container_name: nginx-storage-container
    ports:
      - "8080:80"
    volumes:
      - ftp_data:/usr/share/nginx/html:ro

volumes:
  astro_node_modules:
  ftp_data:
