import type { Restaurante } from "@/Types/Restaurante.ts";

export const restaurantes: Restaurante[] = [
  {
    id: "1",
    name: "La Parrilla Mexicana",
    direccion: "Av. Revolución 102, Ciudad de México",
    phone: "+52 55 1234 5678",
    perfilImage: "/img/fast-food-3.jpg",
    image: "/mva-logo-rb.png",
    amenities: [
      { id: "1", svg: "area-exterior.svg", nombre: "Mesas al aire libre" },
      { id: "2", svg: "delivery.svg", nombre: "Estacionamiento" },
    ],
    categorias: ["Steak House", "Plato Fuerte"],
    horarios: [
      { id: "1", dia: "Martes a jueves", horaApertura: "12:00", horaCierre: "22:00" },
      { id: "2", dia: "Viernes", horaApertura: "12:00", horaCierre: "22:00" },
      { id: "2", dia: "Sábado", horaApertura: "12:00", horaCierre: "22:00" },
      { id: "3", dia: "Domingo", horaApertura: "13:00", horaCierre: "20:00" },
    ],
    tipos: ["Restaurante", "Bar"],
    plan: { id: 1, name: "Premium" },
    horario: "12:00 PM - 10:00 PM",
    menus: [
      {
        id: "m1",
        nombre: "Tacos al Pastor",
        ingredientes: "Cerdo, piña, cebolla, cilantro, salsa roja",
        precio: 95,
        activo: true,
        categoriaId: "1",
        categoria: { id: "1", nombre: "Plato Fuerte" },
        restauranteId: "1",
        imagen: "/images/menus/tacos-al-pastor.jpg",
        ImageFullPath: "/images/menus/tacos-al-pastor.jpg",
      },
    ],
  },
  {
    id: "2",
    name: "Pizzería Bella Italia",
    direccion: "Calle Roma 345, Guadalajara, Jalisco",
    phone: "+52 33 5678 9101",
    perfilImage: "/img/fast-food-3.jpg",
    image: "/mva-logo-rb.png",
    amenities: [
      { id: "3", svg: "<svg>👨‍👩‍👧‍👦</svg>", nombre: "Familiar" },
      { id: "4", svg: "wifi.svg", nombre: "WiFi Gratis" },
    ],
    categorias: ["Pizza", "Pastas", "Postres"],
    horarios: [
      { id: "4", dia: "Miércoles", horaApertura: "13:00", horaCierre: "23:00" },
      { id: "5", dia: "Jueves", horaApertura: "13:00", horaCierre: "23:00" },
      { id: "6", dia: "Viernes", horaApertura: "13:00", horaCierre: "00:00" },
    ],
    tipos: ["Restaurante"],
    plan: { id: 2, name: "Estándar" },
    horario: "1:00 PM - 12:00 AM",
    menus: [
      {
        id: "m2",
        nombre: "Pizza Margarita",
        ingredientes: "Mozzarella, tomate, albahaca fresca, aceite de oliva",
        precio: 140,
        activo: true,
        categoriaId: "2",
        categoria: { id: "2", nombre: "Pizza" },
        restauranteId: "2",
        imagen: "/images/menus/pizza-margarita.jpg",
        ImageFullPath: "/images/menus/pizza-margarita.jpg",
      },
    ],
  },
  {
    id: "3",
    name: "Marisquería El Puerto",
    direccion: "Blvd. del Mar 777, Cancún, Quintana Roo",
    phone: "+52 998 222 3344",
    perfilImage: "/img/fast-food-3.jpg",
    image: "/mva-logo-rb.png",
    amenities: [
      { id: "5", svg: "<svg>🌊</svg>", nombre: "Vista al mar" },
      { id: "6", svg: "<svg>🎶</svg>", nombre: "Música en vivo" },
    ],
    categorias: ["Mariscos", "Pescados", "Bebidas"],
    horarios: [
      { id: "7", dia: "Viernes", horaApertura: "11:00", horaCierre: "22:00" },
      { id: "8", dia: "Sábado", horaApertura: "11:00", horaCierre: "23:00" },
      { id: "9", dia: "Domingo", horaApertura: "11:00", horaCierre: "21:00" },
    ],
    tipos: ["Restaurante", "Terraza"],
    plan: { id: 3, name: "Gold" },
    horario: "11:00 AM - 11:00 PM",
    menus: [
      {
        id: "m3",
        nombre: "Ceviche Mixto",
        ingredientes: "Pescado, camarón, pulpo, limón, cebolla morada, chile",
        precio: 180,
        activo: true,
        categoriaId: "3",
        categoria: { id: "3", nombre: "Mariscos" },
        restauranteId: "3",
        imagen: "/images/menus/ceviche-mixto.jpg",
        ImageFullPath: "/images/menus/ceviche-mixto.jpg",
      },
    ],
  },
];
