// <auto-generated />
using System;
using MVA_FOOD.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVA_FOOD.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250903211523_InitialDB2")]
    partial class InitialDB2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Amenidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Svg")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Amenidades");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.AmenidadRestaurantes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AmenidadId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmenidadId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("AmenidadRestaurantes");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.CategoriaRestaurantes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("CategoriaRestaurantes");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dia")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("HoraApertura")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraCierre")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imagen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredientes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaOcupada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteNombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteTelefono")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MesaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("MesaId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opciones")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItems");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.PlanRestaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pagado")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("RestauranteId")
                        .IsUnique();

                    b.ToTable("PlanesRestaurantes");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Restaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AmenidadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerfilImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanRestauranteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AmenidadId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioNombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Variante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxSeleccion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Obligatorio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Variantes");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.VarianteMenus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VarianteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("VarianteId");

                    b.ToTable("VarianteMenus");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.VarianteOpcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VarianteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VarianteId");

                    b.ToTable("VarianteOpciones");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.AmenidadRestaurantes", b =>
                {
                    b.HasOne("MVA_FOOD.Core.Entities.Amenidad", "Amenidad")
                        .WithMany()
                        .HasForeignKey("AmenidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVA_FOOD.Core.Entities.Restaurante", "Restaurante")
                        .WithMany("AmenidadRestaurantes")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenidad");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.CategoriaRestaurantes", b =>
                {
                    b.HasOne("MVA_FOOD.Core.Entities.Categoria", "Categoria")
                        .WithMany("CategoriaRestaurantes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVA_FOOD.Core.Entities.Restaurante", "Restaurante")
                        .WithMany("CategoriaRestaurantes")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Empleado", b =>
                {
                    b.HasOne("MVA_FOOD.Core.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Horario", b =>
                {
                    b.HasOne("MVA_FOOD.Core.Entities.Restaurante", "Restaurante")
                        .WithMany("Horario")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Menu", b =>
                {
                    b.HasOne("MVA_FOOD.Core.Entities.Categoria", "Categoria")
                        .WithMany("Menus")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVA_FOOD.Core.Entities.Restaurante", "Restaurante")
                        .WithMany("Menu")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Mesa", b =>
                {
                    b.HasOne("MVA_FOOD.Core.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Pedido", b =>
                {
                    b.HasOne("MVA_FOOD.Core.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVA_FOOD.Core.Entities.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVA_FOOD.Core.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Mesa");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.PedidoItem", b =>
                {
                    b.HasOne("MVA_FOOD.Core.Entities.Menu", "Producto")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVA_FOOD.Core.Entities.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.PlanRestaurante", b =>
                {
                    b.HasOne("MVA_FOOD.Core.Entities.Plan", "Plan")
                        .WithMany("PlanesContratados")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVA_FOOD.Core.Entities.Restaurante", "Restaurante")
                        .WithOne("PlanRestaurante")
                        .HasForeignKey("MVA_FOOD.Core.Entities.PlanRestaurante", "RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Restaurante", b =>
                {
                    b.HasOne("MVA_FOOD.Core.Entities.Amenidad", null)
                        .WithMany("Restaurantes")
                        .HasForeignKey("AmenidadId");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Usuario", b =>
                {
                    b.HasOne("MVA_FOOD.Core.Entities.Restaurante", "Restaurante")
                        .WithMany("Usuarios")
                        .HasForeignKey("RestauranteId");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.VarianteMenus", b =>
                {
                    b.HasOne("MVA_FOOD.Core.Entities.Menu", "Menu")
                        .WithMany("VarianteMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVA_FOOD.Core.Entities.Variante", "Variante")
                        .WithMany("MenuVariantes")
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.VarianteOpcion", b =>
                {
                    b.HasOne("MVA_FOOD.Core.Entities.Variante", "Variante")
                        .WithMany("Opciones")
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Amenidad", b =>
                {
                    b.Navigation("Restaurantes");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Categoria", b =>
                {
                    b.Navigation("CategoriaRestaurantes");

                    b.Navigation("Menus");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Menu", b =>
                {
                    b.Navigation("VarianteMenus");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Pedido", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Plan", b =>
                {
                    b.Navigation("PlanesContratados");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Restaurante", b =>
                {
                    b.Navigation("AmenidadRestaurantes");

                    b.Navigation("CategoriaRestaurantes");

                    b.Navigation("Horario");

                    b.Navigation("Menu");

                    b.Navigation("PlanRestaurante");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MVA_FOOD.Core.Entities.Variante", b =>
                {
                    b.Navigation("MenuVariantes");

                    b.Navigation("Opciones");
                });
#pragma warning restore 612, 618
        }
    }
}
